### ISSUE TITLE
Default readline hotkeys: ctrl-w and ctrl-u are wrong.

### ISSUE THREAD

**Issue by wildefyr** [Nanoseb/ncTelegram#1]
Ctrl-w should be used for deleting the previous word (up to last space), while ctrl-u should delete the entire line. Currently ctrl-w has the typical ctrl-u behavior.

As both emacs and vi (in insert mode) respect both of these bindings it's probably best to have these as defaults. Very nice project however.

**Comment by Nanoseb** [comment]
Thanks for the report, this is something I coded at the very beginning and because I forgot it it is still the behaviour. I will change w to u, and maybe later develop the real ctrl-w

**Comment by wildefyr** [comment]
Oh, also, it might be an idea to add 'a' to jump into insert mode as well. I use that more than i with vi usually haha.

**Comment by wildefyr** [comment]
Hate to load this stuff on you, but perhaps Up/Down could go to the previous/next message sent?

**Comment by Nanoseb** [comment]
For the a instead of i you can change that in the config file (just copy /etc/ncTelegram.conf to ~/.ncTelegram.conf before modifying it).
For up/down, you mean to navigate like in a terminal history? it is indeed a kind of expected behaviour in a terminal, but because arrows are also meant to navigate between the various area (the chan list, messages list and input area) I don't know if it is a good idea. But I can make something configurable.
And please don't feel bad contributing!

**Comment by wildefyr** [comment]
I am so used to vi-mode with weechat now, it feels weird not using anything as complete. I'll see what patches I can throw out soon.

**Comment by Nanoseb** [comment]
An other idea would be to use shift+arrows to navigate in the history (I think it is less important than navigating between areas because contrary to a command you almost never wants to resend a message).

**Comment by Nanoseb** [comment]
Oh and when I said 'And please don't feel bad contributing!' I meant, reporting issues and giving idea is contributing, so keep doing it ;)
But if you also want to code no problem.
